# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-hdfs-dn
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    helm.sh/chart: {{ include "hadoop.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hdfs-dn
spec:
  ports:
  {{- range $k, $v := until (int64 .Values.hdfs.dataNode.replicas) }}

  - name: dfs-{{$v}}
    port: {{add (int64 .Values.hdfs.dataNode.externalHTTPPortRangeStart) $v}}
    protocol: TCP
    nodePort: {{add (int64 .Values.hdfs.dataNode.externalHTTPPortRangeStart) $v }}
  - name: webhdfs-{{$v}}
    port: {{add (int64 .Values.hdfs.dataNode.externalDataPortRangeStart) $v }}
    protocol: TCP
    nodePort: {{add (int64 .Values.hdfs.dataNode.externalDataPortRangeStart) $v }}

  {{- end }}
  type: NodePort     
  selector:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hdfs-dn
